// ============================================================
// サービスカテゴリ SEO 設定 (config)
// data/categories.ts のサービス定義に、SEO・キーワードを付与
// TODO: Supabase移行後はServiceCategoryテーブルから取得
// ============================================================

export interface CategoryConfig {
  id: string;
  slug: string;
  name: string;
  shortName: string;
  group: "tatami" | "fusuma" | "shoji" | "washitsu" | "restoration" | "other";
  description: string;
  seoTitle: string; // メタタイトル用
  seoDescription: string; // メタdescription用
  priceFrom?: number;
  unit?: string;
  popular?: boolean;
  keywords: string[]; // 関連キーワード
}

export const CATEGORY_CONFIGS: CategoryConfig[] = [
  {
    id: "tatami-omotegae",
    slug: "tatami-omotegae",
    name: "畳表替え",
    shortName: "表替え",
    group: "tatami",
    description: "畳の表面（ゴザ）だけを新しいものに替える工事。最も一般的な畳のメンテナンスです。",
    seoTitle: "畳の表替え",
    seoDescription: "畳表替えの料金相場・施工事例・口コミで比較。家具移動・即日対応・無料見積もりに対応する畳店を探せます。",
    priceFrom: 3800,
    unit: "枚",
    popular: true,
    keywords: ["畳 表替え", "畳替え 料金", "畳 表替え 相場", "畳 張替え"],
  },
  {
    id: "tatami-uragaeshi",
    slug: "tatami-uragaeshi",
    name: "畳裏返し",
    shortName: "裏返し",
    group: "tatami",
    description: "まだ使える畳表をひっくり返して再利用する工事。コストを抑えたい方に最適です。",
    seoTitle: "畳の裏返し",
    seoDescription: "畳裏返しの料金相場・施工事例・口コミで比較。新畳から3〜5年が目安。費用を抑えて畳を一新できる畳店を探せます。",
    priceFrom: 2500,
    unit: "枚",
    popular: true,
    keywords: ["畳 裏返し", "畳 裏返し 料金", "畳 裏返し 相場"],
  },
  {
    id: "tatami-shinchou",
    slug: "tatami-shinchou",
    name: "畳新調",
    shortName: "新調",
    group: "tatami",
    description: "畳床ごと新しく作り替える工事。傷みが激しい・踏み込みが沈む場合に。",
    seoTitle: "畳の新調（新畳）",
    seoDescription: "畳新調の料金相場・施工事例・口コミで比較。畳床から新しく作り替える工事に対応する畳店を探せます。",
    priceFrom: 12000,
    unit: "枚",
    popular: true,
    keywords: ["畳 新調", "新畳", "畳 入れ替え", "畳 新調 料金"],
  },
  {
    id: "ryukyu-tatami",
    slug: "ryukyu-tatami",
    name: "琉球畳",
    shortName: "琉球畳",
    group: "tatami",
    description: "正方形の縁なし畳。モダンな和室や洋室への設置に人気です。",
    seoTitle: "琉球畳・縁なし畳",
    seoDescription: "琉球畳の料金相場・施工事例・口コミで比較。洋室をモダンな和スペースに変える縁なし畳の施工店を探せます。",
    priceFrom: 15000,
    unit: "枚",
    popular: true,
    keywords: ["琉球畳", "縁なし畳", "琉球畳 料金", "半畳 畳"],
  },
  {
    id: "herinashi-tatami",
    slug: "herinashi-tatami",
    name: "縁なし畳",
    shortName: "縁なし",
    group: "tatami",
    description: "縁（ヘリ）のないシンプルな畳。スタイリッシュな和室に。",
    seoTitle: "縁なし畳",
    seoDescription: "縁なし畳の料金相場・施工事例・口コミで比較。すっきりとモダンな和室を実現する縁なし畳の施工店を探せます。",
    priceFrom: 12000,
    unit: "枚",
    popular: false,
    keywords: ["縁なし畳", "ヘリなし畳", "縁なし畳 料金"],
  },
  {
    id: "washi-tatami",
    slug: "washi-tatami",
    name: "和紙畳",
    shortName: "和紙畳",
    group: "tatami",
    description: "和紙素材の畳表。ダニ・カビが発生しにくく耐久性が高いのが特徴です。",
    seoTitle: "和紙畳",
    seoDescription: "和紙畳の料金相場・施工事例・口コミで比較。ダニ・カビに強く色あせしにくい和紙畳の施工店を探せます。",
    priceFrom: 8000,
    unit: "枚",
    popular: true,
    keywords: ["和紙畳", "和紙畳 デメリット", "和紙畳 料金", "ダイケン 畳"],
  },
  {
    id: "resin-tatami",
    slug: "resin-tatami",
    name: "樹脂畳",
    shortName: "樹脂畳",
    group: "tatami",
    description: "樹脂素材の畳表。水・汚れに強く、ペットやお子様のいるご家庭に人気です。",
    seoTitle: "樹脂畳",
    seoDescription: "樹脂畳の料金相場・施工事例・口コミで比較。水や汚れに強くお手入れが簡単な樹脂畳の施工店を探せます。",
    priceFrom: 9000,
    unit: "枚",
    popular: false,
    keywords: ["樹脂畳", "セキスイ 畳", "樹脂畳 料金"],
  },
  {
    id: "color-tatami",
    slug: "color-tatami",
    name: "カラー畳",
    shortName: "カラー畳",
    group: "tatami",
    description: "グリーン・ブルー・グレーなど色のバリエーションが豊富な畳です。",
    seoTitle: "カラー畳",
    seoDescription: "カラー畳の料金相場・施工事例・口コミで比較。豊富なカラーから選べるおしゃれな畳の施工店を探せます。",
    priceFrom: 9000,
    unit: "枚",
    popular: false,
    keywords: ["カラー畳", "おしゃれ 畳", "カラー畳 料金"],
  },
  {
    id: "kokusan-igusa",
    slug: "kokusan-igusa",
    name: "国産い草",
    shortName: "国産い草",
    group: "tatami",
    description: "熊本県産をはじめとする国産い草を使った高品質な畳。香りと手触りが格別です。",
    seoTitle: "国産い草の畳",
    seoDescription: "国産い草畳の料金相場・施工事例・口コミで比較。熊本産など上質ない草を使った畳の施工店を探せます。",
    priceFrom: 8000,
    unit: "枚",
    popular: false,
    keywords: ["国産 い草", "熊本 い草", "国産畳", "い草 畳"],
  },
  {
    id: "pet-tatami",
    slug: "pet-tatami",
    name: "ペット対応畳",
    shortName: "ペット対応",
    group: "tatami",
    description: "ひっかき傷に強い樹脂畳や和紙畳。ペットと暮らす方に最適です。",
    seoTitle: "ペット対応畳",
    seoDescription: "ペット対応畳の料金相場・施工事例・口コミで比較。傷・汚れ・においに強い畳の施工店を探せます。",
    priceFrom: 9000,
    unit: "枚",
    popular: false,
    keywords: ["ペット 畳", "犬 畳", "猫 畳", "傷つきにくい 畳"],
  },
  {
    id: "fusuma-harikae",
    slug: "fusuma-harikae",
    name: "ふすま張替え",
    shortName: "ふすま",
    group: "fusuma",
    description: "古くなったふすまの張り替え。和室の印象を一新できます。",
    seoTitle: "ふすま（襖）張替え",
    seoDescription: "ふすま張替えの料金相場・施工事例・口コミで比較。和室の印象を一新するふすま張替えの施工店を探せます。",
    priceFrom: 3500,
    unit: "枚",
    popular: true,
    keywords: ["ふすま 張替え", "襖 張替え", "ふすま 張替え 料金"],
  },
  {
    id: "shoji-harikae",
    slug: "shoji-harikae",
    name: "障子張替え",
    shortName: "障子",
    group: "shoji",
    description: "障子紙の張り替え。破れた障子も綺麗に仕上げます。",
    seoTitle: "障子張替え",
    seoDescription: "障子張替えの料金相場・施工事例・口コミで比較。破れ防止・採光性の高い障子紙にも対応する施工店を探せます。",
    priceFrom: 2500,
    unit: "枚",
    popular: true,
    keywords: ["障子 張替え", "障子 張替え 料金", "障子紙 交換"],
  },
  {
    id: "amido-harikae",
    slug: "amido-harikae",
    name: "網戸張替え",
    shortName: "網戸",
    group: "other",
    description: "破れた網戸の張り替え工事。防虫・強化メッシュにも対応します。",
    seoTitle: "網戸張替え",
    seoDescription: "網戸張替えの料金相場・施工事例・口コミで比較。防虫・ペット用強化メッシュにも対応する施工店を探せます。",
    priceFrom: 2000,
    unit: "枚",
    popular: false,
    keywords: ["網戸 張替え", "網戸 張替え 料金", "網戸 交換"],
  },
  {
    id: "washitsu-reform",
    slug: "washitsu-reform",
    name: "和室リフォーム",
    shortName: "和室リフォーム",
    group: "washitsu",
    description: "畳・ふすま・障子・壁をまとめてリフォーム。和室を一新できます。",
    seoTitle: "和室リフォーム",
    seoDescription: "和室リフォームの料金相場・施工事例・口コミで比較。畳・建具・壁をまとめて一新する施工店を探せます。",
    priceFrom: 50000,
    unit: "室",
    popular: true,
    keywords: ["和室 リフォーム", "和室 洋室 リフォーム", "和室 リフォーム 費用"],
  },
  {
    id: "washitsu-sunakabe",
    slug: "washitsu-sunakabe",
    name: "砂壁・聚楽壁リフォーム",
    shortName: "砂壁",
    group: "washitsu",
    description: "古くなった砂壁・聚楽壁の塗り替えや壁紙への貼り替え。",
    seoTitle: "砂壁・聚楽壁リフォーム",
    seoDescription: "砂壁・聚楽壁リフォームの料金相場・施工事例・口コミで比較。塗り替え・壁紙化に対応する施工店を探せます。",
    priceFrom: 15000,
    unit: "室",
    popular: false,
    keywords: ["砂壁 リフォーム", "聚楽壁 塗り替え", "砂壁 壁紙"],
  },
  {
    id: "chashitsu",
    slug: "chashitsu",
    name: "茶室・茶道具部屋",
    shortName: "茶室",
    group: "washitsu",
    description: "茶室特有の炉切り・特殊サイズ畳・茶道向け仕様への対応。",
    seoTitle: "茶室の畳・和室工事",
    seoDescription: "茶室・茶道向けの畳工事の施工事例・口コミで比較。炉切りや特殊寸法に対応する経験豊富な施工店を探せます。",
    priceFrom: 20000,
    unit: "枚",
    popular: false,
    keywords: ["茶室 畳", "炉 畳", "茶道 部屋", "茶室 工事"],
  },
  {
    id: "genjokaihuku",
    slug: "genjokaihuku",
    name: "賃貸原状回復",
    shortName: "原状回復",
    group: "restoration",
    description: "畳・クロス・床をまとめての原状回復対応。管理会社からの依頼も歓迎です。",
    seoTitle: "賃貸の原状回復",
    seoDescription: "賃貸原状回復の料金相場・施工事例・口コミで比較。畳・クロス・床を一括対応する施工店を探せます。",
    priceFrom: 30000,
    unit: "室",
    popular: true,
    keywords: ["原状回復", "賃貸 原状回復", "退去 畳", "原状回復 費用"],
  },
  {
    id: "tatami-beri",
    slug: "tatami-beri",
    name: "畳縁・へり",
    shortName: "畳縁",
    group: "tatami",
    description: "畳縁（へり）のデザイン・色を選んで和室の印象を変える施工。",
    seoTitle: "畳縁（畳へり）",
    seoDescription: "畳縁の種類・デザイン・施工事例で比較。豊富な柄から選べる畳へりに対応する施工店を探せます。",
    priceFrom: 3800,
    unit: "枚",
    popular: false,
    keywords: ["畳縁", "畳へり", "畳 縁 デザイン", "畳 へり 種類"],
  },
  {
    id: "tatami-shindan",
    slug: "tatami-shindan",
    name: "畳点検・診断",
    shortName: "点検・診断",
    group: "other",
    description: "畳床のへたり・湿気・カビなどの状態を点検し、最適な工事を診断します。",
    seoTitle: "畳の点検・診断",
    seoDescription: "畳の点検・診断に対応する施工店を比較。表替え・裏返し・新調のどれが必要か無料で相談できます。",
    priceFrom: 0,
    unit: "式",
    popular: false,
    keywords: ["畳 点検", "畳 診断", "畳 床 へたり", "畳 寿命"],
  },
];

export const CATEGORY_GROUP_LABELS: Record<CategoryConfig["group"], string> = {
  tatami: "畳",
  fusuma: "ふすま",
  shoji: "障子",
  washitsu: "和室",
  restoration: "原状回復",
  other: "その他",
};

export function getCategoryConfigBySlug(slug: string): CategoryConfig | undefined {
  return CATEGORY_CONFIGS.find((c) => c.slug === slug);
}

export function getCategoryConfigsByGroup(group: CategoryConfig["group"]): CategoryConfig[] {
  return CATEGORY_CONFIGS.filter((c) => c.group === group);
}

export const POPULAR_CATEGORY_CONFIGS = CATEGORY_CONFIGS.filter((c) => c.popular);
