// ============================================================
// 市区町村 SEO 設定 (config)
// data/cities.ts を元に、SEO・内部リンク用のメタ情報を付与
// TODO: Supabase移行後はCityテーブルから取得
// ============================================================

export interface CityConfig {
  id: string;
  slug: string; // URLスラッグ (例: "kawaguchi")
  name: string; // 表示名 (例: "川口市")
  nameKana?: string; // かな
  postalCode?: string;
  description: string; // SEO用説明（100字以内）
  seoNote?: string; // 畳工事の地域特性
  nearbyIds: string[]; // 近隣エリアのid
  popularCategories: string[]; // 人気カテゴリのslug
}

const DEFAULT_POPULAR = ["tatami-omotegae", "tatami-shinchou", "fusuma-harikae", "shoji-harikae"];

export const CITY_CONFIGS: CityConfig[] = [
  {
    id: "saitama",
    slug: "saitama-city",
    name: "さいたま市",
    nameKana: "さいたまし",
    postalCode: "330-0000",
    description: "埼玉県の県庁所在地・政令指定都市。戸建て・マンションが多く、畳表替えや和室リフォームの需要が高いエリアです。",
    seoNote: "浦和・大宮を中心に住宅が密集。家具移動込みの表替えや、マンションの和室リフォーム依頼が多い傾向です。",
    nearbyIds: ["kawaguchi", "ageo", "toda", "warabi", "koshigaya"],
    popularCategories: ["tatami-omotegae", "washitsu-reform", "fusuma-harikae", "ryukyu-tatami"],
  },
  {
    id: "kawaguchi",
    slug: "kawaguchi",
    name: "川口市",
    nameKana: "かわぐちし",
    postalCode: "332-0000",
    description: "東京に隣接する人口60万人超の住宅都市。賃貸物件が多く、原状回復や畳表替えの依頼が活発なエリアです。",
    seoNote: "賃貸物件の退去に伴う畳の表替え・原状回復ニーズが高く、管理会社からの一括依頼にも対応できる業者が揃います。",
    nearbyIds: ["saitama", "warabi", "toda", "soka"],
    popularCategories: ["tatami-omotegae", "rental-tatami", "genjoukaifuku", "fusuma-harikae"],
  },
  {
    id: "kawagoe",
    slug: "kawagoe",
    name: "川越市",
    nameKana: "かわごえし",
    postalCode: "350-0000",
    description: "「小江戸」と呼ばれる歴史観光都市。古民家・旅館・茶室など、特殊な和室の畳工事ニーズが豊富です。",
    seoNote: "歴史的建物が多く、特注寸法の畳新調や茶室対応など、技術力の高い畳店が活躍するエリアです。",
    nearbyIds: ["tokorozawa", "sayama", "fujimino", "saitama"],
    popularCategories: ["tatami-shinchou", "chasitsu", "tatami-omotegae", "washitsu-reform"],
  },
  {
    id: "koshigaya",
    slug: "koshigaya",
    name: "越谷市",
    nameKana: "こしがやし",
    postalCode: "343-0000",
    description: "東武スカイツリーライン沿いの住宅都市。戸建てと賃貸が混在し、畳・ふすま・障子の張替え依頼が多いエリアです。",
    seoNote: "ファミリー世帯の戸建てが多く、和室の表替えやふすま・障子の張替えをまとめて依頼するケースが目立ちます。",
    nearbyIds: ["soka", "kasukabe", "saitama", "misato"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "tokorozawa",
    slug: "tokorozawa",
    name: "所沢市",
    nameKana: "ところざわし",
    postalCode: "359-0000",
    description: "西武沿線の住宅都市。閑静な住宅地が広がり、和室リフォームや琉球畳への張替え相談が増えています。",
    seoNote: "築年数の経った戸建てが多く、和室を活かしたリフォームや縁なし畳・琉球畳への変更が人気です。",
    nearbyIds: ["kawagoe", "sayama", "iruma", "niiza"],
    popularCategories: ["tatami-omotegae", "ryukyu-tatami", "washitsu-reform", "fusuma-harikae"],
  },
  {
    id: "soka",
    slug: "soka",
    name: "草加市",
    nameKana: "そうかし",
    postalCode: "340-0000",
    description: "東京へのアクセスが良い下町情緒のある住宅都市。賃貸・戸建ての畳表替えや原状回復に対応する業者が揃います。",
    seoNote: "東武線沿線の賃貸需要が高く、退去時の原状回復・畳表替えの相談が多いエリアです。",
    nearbyIds: ["kawaguchi", "koshigaya", "yashio", "misato"],
    popularCategories: ["tatami-omotegae", "rental-tatami", "fusuma-harikae", "shoji-harikae"],
  },
  {
    id: "kasukabe",
    slug: "kasukabe",
    name: "春日部市",
    nameKana: "かすかべし",
    postalCode: "344-0000",
    description: "東武線沿線の住宅都市。戸建てが多く、和室リフォームや畳の新調・表替えのニーズが高いエリアです。",
    seoNote: "築年数の経った和室を持つ住宅が多く、表替えと併せたふすま・障子の張替え依頼が増えています。",
    nearbyIds: ["koshigaya", "kuki", "saitama"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "ageo",
    slug: "ageo",
    name: "上尾市",
    nameKana: "あげおし",
    postalCode: "362-0000",
    description: "さいたま市に隣接するベッドタウン。賃貸・戸建てが多く、畳表替えや原状回復の需要が安定しています。",
    seoNote: "ファミリー向け住宅と賃貸が混在し、表替え・新調から原状回復まで幅広い相談に対応できます。",
    nearbyIds: ["saitama", "kounosu", "kawagoe"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "kumagaya",
    slug: "kumagaya",
    name: "熊谷市",
    nameKana: "くまがやし",
    postalCode: "360-0000",
    description: "北埼玉の中心都市。戸建て住宅が多く、和室の畳表替えや新調、ふすま張替えの依頼が活発です。",
    seoNote: "夏の高温で知られる地域。畳の湿気・カビ対策やダニ対策素材への張替え相談も多いエリアです。",
    nearbyIds: ["fukaya", "gyoda", "honjo", "kounosu"],
    popularCategories: ["tatami-omotegae", "tatami-shinchou", "mold-dani-tatami", "fusuma-harikae"],
  },
  {
    id: "toda",
    slug: "toda",
    name: "戸田市",
    nameKana: "とだし",
    postalCode: "335-0000",
    description: "東京アクセス良好なマンションの多い都市。マンション和室の畳表替え・琉球畳への張替えが人気です。",
    seoNote: "マンション率が高く、洋室に琉球畳・縁なし畳を敷くモダンな和スペースづくりの相談が増えています。",
    nearbyIds: ["warabi", "kawaguchi", "saitama"],
    popularCategories: ["tatami-omotegae", "ryukyu-tatami", "herinashi-tatami", "fusuma-harikae"],
  },
  {
    id: "warabi",
    slug: "warabi",
    name: "蕨市",
    nameKana: "わらびし",
    postalCode: "335-0000",
    description: "日本一面積の小さい市。都市型の賃貸物件が多く、原状回復・畳表替えの依頼が活発なエリアです。",
    seoNote: "コンパクトな賃貸物件が密集し、退去に伴う畳・ふすまの張替えや原状回復の需要が安定しています。",
    nearbyIds: ["toda", "kawaguchi", "saitama"],
    popularCategories: ["tatami-omotegae", "rental-tatami", "genjoukaifuku", "fusuma-harikae"],
  },
  {
    id: "asaka",
    slug: "asaka",
    name: "朝霞市",
    nameKana: "あさかし",
    postalCode: "351-0000",
    description: "東京近郊の閑静な住宅地。戸建て・賃貸ともに多く、畳表替えや和室リフォームの相談が増えています。",
    seoNote: "ファミリー層が多く、和室を子ども部屋や客間として活かすリフォーム・畳張替えが人気です。",
    nearbyIds: ["wako", "niiza", "shiki", "saitama"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "shiki",
    slug: "shiki",
    name: "志木市",
    nameKana: "しきし",
    postalCode: "354-0000",
    description: "荒川沿いの住宅都市。戸建てと集合住宅が混在し、畳・ふすま・障子の張替え依頼が多いエリアです。",
    seoNote: "落ち着いた住宅地で、和室メンテナンスの定期的な表替え・裏返しの相談が安定しています。",
    nearbyIds: ["asaka", "niiza", "fujimi", "wako"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "wako",
    slug: "wako",
    name: "和光市",
    nameKana: "わこうし",
    postalCode: "351-0100",
    description: "東京に隣接する文教地区。マンション・賃貸が多く、和室の畳表替えや原状回復の需要が安定しています。",
    seoNote: "転勤・単身世帯の入退去が多く、賃貸の原状回復・畳表替えの依頼に強い業者が活躍します。",
    nearbyIds: ["asaka", "niiza", "saitama"],
    popularCategories: ["tatami-omotegae", "rental-tatami", "fusuma-harikae", "shoji-harikae"],
  },
  {
    id: "niiza",
    slug: "niiza",
    name: "新座市",
    nameKana: "にいざし",
    postalCode: "352-0000",
    description: "西武池袋線沿線の住宅都市。戸建てが多く、和室リフォームや畳の新調・表替えの相談が増えています。",
    seoNote: "古くからの戸建てが多く、和室を活かしたリフォームと畳・建具の一括張替えが人気です。",
    nearbyIds: ["asaka", "shiki", "tokorozawa", "wako"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "fujimi",
    slug: "fujimi",
    name: "富士見市",
    nameKana: "ふじみし",
    postalCode: "354-0000",
    description: "荒川沿いに広がる住宅都市。ファミリー世帯が多く、畳表替え・ふすま張替えの依頼が活発です。",
    seoNote: "新旧の住宅が混在し、和室メンテナンスからリフォームまで幅広い相談に対応できます。",
    nearbyIds: ["fujimino", "shiki", "kawagoe"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "fujimino",
    slug: "fujimino",
    name: "ふじみ野市",
    nameKana: "ふじみのし",
    postalCode: "356-0000",
    description: "東武東上線沿線の住宅都市。戸建て・賃貸が混在し、畳・建具の張替えニーズが安定しています。",
    seoNote: "ファミリー向け住宅が多く、表替え・新調と併せたふすま・障子張替えの相談が増えています。",
    nearbyIds: ["fujimi", "kawagoe", "tokorozawa"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "misato",
    slug: "misato",
    name: "三郷市",
    nameKana: "みさとし",
    postalCode: "341-0000",
    description: "千葉・東京に隣接する住宅都市。TX沿線で開発が進み、畳表替えや原状回復の依頼が活発です。",
    seoNote: "賃貸・分譲が混在し、退去時の畳張替え・原状回復から新調まで幅広く対応できます。",
    nearbyIds: ["yashio", "soka", "koshigaya"],
    popularCategories: ["tatami-omotegae", "rental-tatami", "genjoukaifuku", "fusuma-harikae"],
  },
  {
    id: "yashio",
    slug: "yashio",
    name: "八潮市",
    nameKana: "やしおし",
    postalCode: "340-0800",
    description: "TX沿線で開発が進む都市。新旧の住宅が混在し、畳表替えやふすま張替えの需要が高まっています。",
    seoNote: "新興住宅と古くからの住宅が共存し、表替え・新調・建具張替えと相談内容が多彩です。",
    nearbyIds: ["misato", "soka", "koshigaya"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "kuki",
    slug: "kuki",
    name: "久喜市",
    nameKana: "くきし",
    postalCode: "346-0000",
    description: "東北自動車道の要衝。住宅と工業が混在し、戸建ての畳表替え・新調の依頼が安定しています。",
    seoNote: "戸建て住宅が多く、和室の表替え・新調とふすま・障子の張替えをまとめて依頼するケースが目立ちます。",
    nearbyIds: ["kasukabe", "gyoda", "kazo", "koshigaya"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "sayama",
    slug: "sayama",
    name: "狭山市",
    nameKana: "さやまし",
    postalCode: "350-1300",
    description: "「狭山茶」の産地として知られる西武沿線の都市。和室を持つ戸建てが多く、畳工事の需要が安定しています。",
    seoNote: "茶の産地らしく和室文化が根付き、茶室・床の間を含む畳工事の相談にも対応できます。",
    nearbyIds: ["iruma", "tokorozawa", "kawagoe", "hanno"],
    popularCategories: ["tatami-omotegae", "chasitsu", "tatami-shinchou", "fusuma-harikae"],
  },
  {
    id: "iruma",
    slug: "iruma",
    name: "入間市",
    nameKana: "いるまし",
    postalCode: "358-0000",
    description: "茶畑と住宅地が広がる西武沿線の都市。戸建ての和室を中心に畳表替え・新調の依頼が活発です。",
    seoNote: "落ち着いた住宅地で、定期的な表替え・裏返しや和室リフォームの相談が安定しています。",
    nearbyIds: ["sayama", "tokorozawa", "hanno"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "hanno",
    slug: "hanno",
    name: "飯能市",
    nameKana: "はんのうし",
    postalCode: "357-0000",
    description: "奥武蔵・秩父の玄関口。観光・宿泊施設が多く、旅館や民泊の畳工事ニーズが高いエリアです。",
    seoNote: "宿泊施設の客室畳の一括施工や、耐久性の高い素材への張替え相談に対応できる業者が活躍します。",
    nearbyIds: ["sayama", "iruma", "chichibu"],
    popularCategories: ["tatami-omotegae", "ryokan-tatami", "tatami-shinchou", "washitsu-reform"],
  },
  {
    id: "higashimatsuyama",
    slug: "higashimatsuyama",
    name: "東松山市",
    nameKana: "ひがしまつやまし",
    postalCode: "355-0000",
    description: "中部埼玉の中核都市。戸建て住宅が多く、和室の畳表替え・新調やふすま張替えの依頼が安定しています。",
    seoNote: "ファミリー世帯の戸建てが多く、和室メンテナンスとリフォームの相談が幅広く寄せられます。",
    nearbyIds: ["kawagoe", "kumagaya", "fukaya"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "fukaya",
    slug: "fukaya",
    name: "深谷市",
    nameKana: "ふかやし",
    postalCode: "366-0000",
    description: "渋沢栄一ゆかりの農業と歴史の街。戸建てが多く、和室の畳表替え・新調の需要が安定しています。",
    seoNote: "古くからの住宅が多く、特注寸法の畳や床の間を含む和室工事の相談にも対応できます。",
    nearbyIds: ["kumagaya", "honjo", "higashimatsuyama"],
    popularCategories: ["tatami-omotegae", "tatami-shinchou", "fusuma-harikae", "washitsu-reform"],
  },
  {
    id: "honjo",
    slug: "honjo",
    name: "本庄市",
    nameKana: "ほんじょうし",
    postalCode: "367-0000",
    description: "旧中山道の宿場町。歴史ある住宅が多く、和室の畳工事やふすま・障子の張替えニーズが高いエリアです。",
    seoNote: "古い家屋が残り、畳新調や床の間・特殊寸法への対応など技術力が求められる現場が多くあります。",
    nearbyIds: ["fukaya", "kumagaya"],
    popularCategories: ["tatami-omotegae", "tatami-shinchou", "fusuma-harikae", "shoji-harikae"],
  },
  {
    id: "kounosu",
    slug: "kounosu",
    name: "鴻巣市",
    nameKana: "こうのすし",
    postalCode: "365-0000",
    description: "ひなまつりで知られる中央埼玉の都市。戸建てが多く、和室の畳表替え・新調の需要が安定しています。",
    seoNote: "ひな人形文化が根付く地域で、客間・和室を整える畳・建具の張替え相談が多くあります。",
    nearbyIds: ["ageo", "gyoda", "kumagaya"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "gyoda",
    slug: "gyoda",
    name: "行田市",
    nameKana: "ぎょうだし",
    postalCode: "361-0000",
    description: "「足袋の産地」として知られる歴史ある都市。戸建ての和室を中心に畳工事の依頼が安定しています。",
    seoNote: "歴史的建物や古い住宅が多く、畳新調や床の間を含む和室工事の相談に対応できます。",
    nearbyIds: ["kumagaya", "kounosu", "kuki", "kazo"],
    popularCategories: ["tatami-omotegae", "tatami-shinchou", "fusuma-harikae", "washitsu-reform"],
  },
  {
    id: "kazo",
    slug: "kazo",
    name: "加須市",
    nameKana: "かぞし",
    postalCode: "347-0000",
    description: "うどんと鯉のぼりで知られる利根川沿いの都市。戸建ての和室を中心に畳工事の需要が安定しています。",
    seoNote: "農村部の広い和室を持つ住宅が多く、複数室の畳表替え・新調をまとめて依頼するケースが目立ちます。",
    nearbyIds: ["kuki", "gyoda", "hanyu"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "hanyu",
    slug: "hanyu",
    name: "羽生市",
    nameKana: "はにゅうし",
    postalCode: "348-0000",
    description: "利根川沿いの農業都市。戸建て住宅が多く、和室の畳表替え・新調やふすま張替えの依頼が安定しています。",
    seoNote: "広い和室を持つ住宅が多く、複数室の畳工事や建具の一括張替えの相談に対応できます。",
    nearbyIds: ["kazo", "gyoda", "kuki"],
    popularCategories: DEFAULT_POPULAR,
  },
  {
    id: "chichibu",
    slug: "chichibu",
    name: "秩父市",
    nameKana: "ちちぶし",
    postalCode: "368-0000",
    description: "秩父神社・秩父夜祭で知られる観光都市。旅館・寺社の畳工事や和室メンテナンスのニーズが高いエリアです。",
    seoNote: "寺社・旅館が多く、本堂や客室の格式ある畳工事に対応できる経験豊富な業者が活躍します。",
    nearbyIds: ["hanno", "sayama"],
    popularCategories: ["tatami-omotegae", "temple-shrine-tatami", "ryokan-tatami", "tatami-shinchou"],
  },
];

export function getCityConfigBySlug(slug: string): CityConfig | undefined {
  return CITY_CONFIGS.find((c) => c.slug === slug);
}

export function getCityConfigById(id: string): CityConfig | undefined {
  return CITY_CONFIGS.find((c) => c.id === id);
}

export function getNearbyCities(slug: string): CityConfig[] {
  const city = getCityConfigBySlug(slug);
  if (!city) return [];
  return city.nearbyIds
    .map((id) => getCityConfigById(id))
    .filter((c): c is CityConfig => Boolean(c) && c!.slug !== slug);
}
